# Generated by Django 5.0.4 on 2024-04-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consume',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='fat',
            new_name='fats',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='protine',
            new_name='protein',
        ),
    ]
